sudo: required

language: go

arch:
  - amd64
  - arm64
go:
  - "1.15"

env:
  - DB_USER=root DB_PASSWORD=test123456 DB_HOST=127.0.0.1 DB_PORT=13306 REDIS_HOST=127.0.0.1 REDIS_PORT=16379 API_PORT=18080 API_HOST=127.0.0.1

services:
  - docker

before_install:
  - tmpdaemon=$(mktemp)
  - sudo jq '."registry-mirrors" += ["https://mirror.gcr.io"]' /etc/docker/daemon.json > $tmpdaemon
  - sudo mv $tmpdaemon /etc/docker/daemon.json
  - sudo systemctl daemon-reload
  - sudo systemctl restart docker
  - docker system info

script:
  - go get -u github.com/go-sql-driver/mysql
  - make fmt
  - make fmt-check
  - make misspell-check
  - make all
  - bash ./docker_test.sh

after_success:
  - go test -race -coverprofile=coverage.txt -covermode=atomic github.com/wenchangshou/falcon-plus/modules/api/test
  - bash <(curl -s https://codecov.io/bash)
